#! /usr/bin/env bash

cd modules

for dir in */; do
    cd "$dir"
    
    make clean
    make

    retVal=$?
    if [ $retVal -ne 0 ]; then
        exit $retVal
    fi

    make clean

    cd ..
done